[package]
name = "node-template-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
pallet-aura = { path = "../../../frame/aura", default-features = false }
sp-consensus-aura = { path = "../../../primitives/consensus/aura", default-features = false }
pallet-balances = { path = "../../../frame/balances", default-features = false }
sp-block-builder = { path = "../../../primitives/block-builder", default-features = false}
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
frame-executive = { path = "../../../frame/executive", default-features = false }
pallet-grandpa = { path = "../../../frame/grandpa", default-features = false }
pallet-indices = { path = "../../../frame/indices", default-features = false }
sp-inherents = { path = "../../../primitives/inherents", default-features = false}
sp-offchain = { path = "../../../primitives/offchain", default-features = false }
sp-core = { path = "../../../primitives/core", default-features = false }
pallet-randomness-collective-flip = { path = "../../../frame/randomness-collective-flip", default-features = false }
sp-std = { path = "../../../primitives/std", default-features = false }
sp-io = { path = "../../../primitives/io", default-features = false }
safe-mix = { version = "1.0.0", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { path = "../../../primitives/api", default-features = false }
sp-runtime = { path = "../../../primitives/runtime", default-features = false }
sp-session = { path = "../../../primitives/session", default-features = false }
pallet-sudo = { path = "../../../frame/sudo", default-features = false }
frame-support = { path = "../../../frame/support", default-features = false }
frame-system = { path = "../../../frame/system", default-features = false }
pallet-timestamp = { path = "../../../frame/timestamp", default-features = false }
pallet-transaction-payment = { path = "../../../frame/transaction-payment", default-features = false }
sp-transaction-pool = { path = "../../../primitives/transaction-pool", default-features = false }
sp-version = { path = "../../../primitives/version", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", path = "../../../utils/wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"sp-consensus-aura/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"frame-executive/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"sp-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-runtime/std",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"sp-transaction-pool/std",
	"sp-version/std",
]
